// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUzcpaFTMaqhaXZhkBiFqfVNiKZZsSq8',
    appId: '1:979081402191:web:77112832c728ec78cfd73a',
    messagingSenderId: '979081402191',
    projectId: 'agri-mart-0304',
    authDomain: 'agri-mart-0304.firebaseapp.com',
    storageBucket: 'agri-mart-0304.appspot.com',
    measurementId: 'G-RZFD4CRXXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-gl9BJ5P_H2-GfhOqn5nWgrfHnl4iJ0',
    appId: '1:979081402191:android:81cf49724e1b5db2cfd73a',
    messagingSenderId: '979081402191',
    projectId: 'agri-mart-0304',
    storageBucket: 'agri-mart-0304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTAoiCAzD-wrQLT_5FdJOljScYu5z_9wk',
    appId: '1:979081402191:ios:36b3241ad619fd4ccfd73a',
    messagingSenderId: '979081402191',
    projectId: 'agri-mart-0304',
    storageBucket: 'agri-mart-0304.appspot.com',
    iosBundleId: 'com.example.buyerMart1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTAoiCAzD-wrQLT_5FdJOljScYu5z_9wk',
    appId: '1:979081402191:ios:36b3241ad619fd4ccfd73a',
    messagingSenderId: '979081402191',
    projectId: 'agri-mart-0304',
    storageBucket: 'agri-mart-0304.appspot.com',
    iosBundleId: 'com.example.buyerMart1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuUzcpaFTMaqhaXZhkBiFqfVNiKZZsSq8',
    appId: '1:979081402191:web:09c43fbab7eb5028cfd73a',
    messagingSenderId: '979081402191',
    projectId: 'agri-mart-0304',
    authDomain: 'agri-mart-0304.firebaseapp.com',
    storageBucket: 'agri-mart-0304.appspot.com',
    measurementId: 'G-81M27TT2TY',
  );

}